/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DocumentId = IDL.Nat;
export const FolderId = IDL.Nat;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'hasSeenSampleData' : IDL.Bool,
});
export const Time = IDL.Int;
export const Document = IDL.Record({
  'id' : DocumentId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
  'folderId' : IDL.Opt(FolderId),
});
export const DocumentVersion = IDL.Record({
  'versionId' : IDL.Nat,
  'content' : IDL.Text,
  'savedAt' : Time,
  'documentId' : DocumentId,
});
export const Folder = IDL.Record({
  'id' : FolderId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDocument' : IDL.Func([IDL.Text, IDL.Text], [DocumentId], []),
  'createFolder' : IDL.Func([IDL.Text], [FolderId], []),
  'deleteDocument' : IDL.Func([DocumentId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocument' : IDL.Func([DocumentId], [Document], ['query']),
  'getDocumentHistory' : IDL.Func(
      [DocumentId],
      [IDL.Vec(DocumentVersion)],
      ['query'],
    ),
  'getUserDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'getUserFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'moveDocumentToFolder' : IDL.Func([DocumentId, FolderId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchDocumentsByTitle' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'updateDocument' : IDL.Func([DocumentId, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DocumentId = IDL.Nat;
  const FolderId = IDL.Nat;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'hasSeenSampleData' : IDL.Bool,
  });
  const Time = IDL.Int;
  const Document = IDL.Record({
    'id' : DocumentId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'updatedAt' : Time,
    'folderId' : IDL.Opt(FolderId),
  });
  const DocumentVersion = IDL.Record({
    'versionId' : IDL.Nat,
    'content' : IDL.Text,
    'savedAt' : Time,
    'documentId' : DocumentId,
  });
  const Folder = IDL.Record({
    'id' : FolderId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDocument' : IDL.Func([IDL.Text, IDL.Text], [DocumentId], []),
    'createFolder' : IDL.Func([IDL.Text], [FolderId], []),
    'deleteDocument' : IDL.Func([DocumentId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocument' : IDL.Func([DocumentId], [Document], ['query']),
    'getDocumentHistory' : IDL.Func(
        [DocumentId],
        [IDL.Vec(DocumentVersion)],
        ['query'],
      ),
    'getUserDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'getUserFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'moveDocumentToFolder' : IDL.Func([DocumentId, FolderId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchDocumentsByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'updateDocument' : IDL.Func([DocumentId, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };