/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Document {
  'id' : DocumentId,
  'title' : string,
  'content' : string,
  'owner' : Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
  'folderId' : [] | [FolderId],
}
export type DocumentId = bigint;
export interface DocumentVersion {
  'versionId' : bigint,
  'content' : string,
  'savedAt' : Time,
  'documentId' : DocumentId,
}
export interface Folder {
  'id' : FolderId,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
}
export type FolderId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string, 'hasSeenSampleData' : boolean }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDocument' : ActorMethod<[string, string], DocumentId>,
  'createFolder' : ActorMethod<[string], FolderId>,
  'deleteDocument' : ActorMethod<[DocumentId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocument' : ActorMethod<[DocumentId], Document>,
  'getDocumentHistory' : ActorMethod<[DocumentId], Array<DocumentVersion>>,
  'getUserDocuments' : ActorMethod<[], Array<Document>>,
  'getUserFolders' : ActorMethod<[], Array<Folder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'moveDocumentToFolder' : ActorMethod<[DocumentId, FolderId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchDocumentsByTitle' : ActorMethod<[string], Array<Document>>,
  'updateDocument' : ActorMethod<[DocumentId, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];